version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql-node-codeeducation
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - app-network

  node-app:
    build: ./node-app
    container_name: node-app-codeeducation
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-codeeducation
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - node-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge